dashboard/dashboard/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('dashboard/', include('myapp.urls')),
]

dashboard/myapp/urls.py
from django.urls import path
from . import views

app_name = "dashboard"

urlpatterns = [
    path("", views.index, name="dashboard"),
    path("charts/", views.charts, name="charts"),
    path("tables/", views.tables, name="tables"),
]

dashboard/myapp/models.py
from django.db import models


class DashboardData(models.Model):
    end_year = models.CharField(max_length=10, blank=True, null=True)
    intensity = models.IntegerField(null=True)
    sector = models.CharField(max_length=100)
    topic = models.CharField(max_length=100)
    insight = models.TextField()
    url = models.URLField()
    region = models.CharField(max_length=100)
    start_year = models.CharField(max_length=10, blank=True, null=True)
    impact = models.CharField(max_length=100, blank=True, null=True)
    added = models.CharField(max_length=50, blank=True, null=True)
    published = models.CharField(max_length=50, blank=True, null=True)
    country = models.CharField(max_length=100)
    relevance = models.IntegerField(null=True)
    pestle = models.CharField(max_length=100)
    source = models.CharField(max_length=100)
    title = models.CharField(max_length=255)
    likelihood = models.IntegerField(null=True)

    def __str__(self):
        return self.title
    

dashboard/myapp/views.py
from django.shortcuts import render
from .models import DashboardData
import json
# Create your views here.
def index(request):
    country_count = DashboardData.objects.values('country').distinct().count()
    topics__count = DashboardData.objects.values('topic').distinct().count()
    region__count = DashboardData.objects.values('region').distinct().count()
    sector__count = DashboardData.objects.values('region').distinct().count()
    return render(request, 'dashboard/index.html', {'country_count': country_count,
                                                    'topics__count':topics__count,
                                                    'region_count':region__count,
                                                    'sector_count':sector__count})
    
def charts(request):
    data = DashboardData.objects.all()

    # Access model fields correctly
    sectors = [entry.sector for entry in data]
    intensities = [entry.intensity for entry in data]

    context = {
        'sectors': json.dumps(sectors),
        'intensities': json.dumps(intensities),
    }

    return render(request, 'dashboard/charts.html', context)

def tables(request):
    region_value = request.GET.get('region', None)
    endyear_value = request.GET.get('end_year', None)
    topics_value = request.GET.get('topic', None)
    sector_value = request.GET.get('sector', None)
    source_value = request.GET.get('source', None)

    data = DashboardData.objects.all()

    if region_value:
        data = data.filter(region=region_value)
    if endyear_value:
        data = data.filter(end_year=endyear_value)
    if topics_value:
        data = data.filter(topic=topics_value)
    if sector_value:
        data = data.filter(sector=sector_value)
    if source_value:
        data = data.filter(source=source_value)

    region_filter = DashboardData.objects.values('region').distinct()
    endyear_filter = DashboardData.objects.values('end_year').distinct()
    topics_filter = DashboardData.objects.values('topic').distinct()
    sector_filter = DashboardData.objects.values('sector').distinct()
    source_filter = DashboardData.objects.values('source').distinct()

    return render(request, 'dashboard/tables.html', {
        'data': data,
        'region_filter': region_filter,
        'endyear_filter': endyear_filter,
        'topics_filter': topics_filter,
        'sector_filter': sector_filter,
        'source_filter': source_filter
    })

dashboard/myapp/templates/base.html
{% load static %}

{% block html %}
<!DOCTYPE html>
<html dir="ltr" lang="en">
{% block head %}
   <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'images/favicon.png' %}">
    <title>Visualization Dashboard</title>
            <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet"/>
            <link href="{% static 'css/animation.css' %}" rel="stylesheet"/>
            <link href="{% static 'css/asColorPicker.min.css' %}" rel="stylesheet"/>
            <link href="{% static 'css/fullcalendar.min.css' %}" rel="stylesheet"/>
            <link href="{% static 'css/calendar.css' %}" rel="stylesheet"/>
            <link href="{% static 'css/dataTables.bootstrap4.min.css' %}" rel="stylesheet"/>
            <link href="{% static 'css/responsive.bootstrap4.min.css' %}" rel="stylesheet"/>
            <link href="{% static 'css/fontawesome-all.min.css' %}" rel="stylesheet"/>
            <link href="{% static 'css/jquery.gritter.css' %}" rel="stylesheet"/>
            <link href="{% static 'css/jquery.minicolors.css' %}" rel="stylesheet"/>
            <link href="{% static 'css/jquery.steps.css' %}" rel="stylesheet"/>
            <link href="{% static 'css/magnific-popup.css' %}" rel="stylesheet"/>
            <link href="{% static 'css/materialdesignicons.min.css' %}" rel="stylesheet"/>
            <link href="{% static 'css/multicheck.css' %}" rel="stylesheet"/>
            <link href="{% static 'css/perfect-scrollbar.min.css' %}" rel="stylesheet"/>
            <link href="{% static 'css/quill.core.css' %}" rel="stylesheet"/>
            <link href="{% static 'css/quill.snow.css' %}" rel="stylesheet"/>
            <link href="{% static 'css/select2.min.css' %}" rel="stylesheet"/>
            <link href="{% static 'css/steps.css' %}" rel="stylesheet"/>
            <link href="{% static 'css/themify-icons.css' %}" rel="stylesheet"/>
            <link href="{% static 'css/toastr.min.css' %}" rel="stylesheet"/>
            <link href="{% static 'css/weather-icons.css' %}" rel="stylesheet"/>
            <link href="{% static 'css/weather-icons.min.css' %}" rel="stylesheet"/>
            <link href="{% static 'css/float-chart.css' %}" rel="stylesheet"/>
            <link href="{% static 'css/style.min.css' %}" rel="stylesheet"/>
            <link href="{% static 'css/custom.css' %}" rel="stylesheet"/>
            <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
      {% block extra_style %}{% endblock extra_style %}
</head>
{% endblock head %}
   
    {% block body %}
   
    <body>
    <div id="main-wrapper">
         {% include 'dashboard/includes/header.html' %}
         {% include 'dashboard/includes/sidebar.html' %}
          <div class="page-wrapper">
           {% block content %}{% endblock content %}
           {% include 'dashboard/includes/footer.html' %}
         </div>
    </div>

    {% block script %}
    
        <script src="{% static 'js/jquery.min.js' %}"></script>
        <script src="{% static 'js/popper.min.js' %}"></script>
        <script src="{% static 'js/bootstrap.min.js' %}"></script>
        <script src="{% static 'js/perfect-scrollbar.jquery.min.js' %}"></script>
        <script src="{% static 'js/sparkline.js' %}"></script>
        <script src="{% static 'js/waves.js' %}"></script>
        <script src="{% static 'js/sidebarmenu.js' %}"></script>
        <script src="{% static 'js/custom.min.js' %}"></script>
        <script src="{% static 'js/excanvas.js' %}"></script>
        <script src="{% static 'js/jquery.flot.js' %}"></script>
        <script src="{% static 'js/jquery.flot.pie.js' %}"></script>
        <script src="{% static 'js/jquery.flot.time.js' %}"></script>
        <script src="{% static 'js/jquery.flot.time.js' %}"></script>
        <script src="{% static 'js/jquery.flot.stack.js' %}"></script>
        <script src="{% static 'js/jquery.flot.crosshair.js' %}"></script>
        <script src="{% static 'js/jquery.flot.tooltip.min.js' %}"></script>
        <script src="{% static 'js/moment.min.js' %}"></script>
        <script src="{% static 'js/chart-page-init.js' %}"></script>
        <script src="{% static 'js/app-style-switcher.js' %}"></script>
        <script src="{% static 'js/bootstrap-datepicker.min.js' %}"></script>
        <script src="{% static 'js/datatable-checkbox-init.js' %}"></script>
        <script src="{% static 'js/datatables.min.js' %}"></script>
        <script src="{% static 'js/jquery.dataTables.min.js' %}"></script>
        <script src="{% static 'js/dataTables.bootstrap4.min.js' %}"></script>
        <script src="{% static 'js/dataTables.responsive.min.js' %}"></script>
        <script src="{% static 'js/responsive.bootstrap4.min.js' %}"></script>
        <script src="{% static 'js/jquery.charts-sparkline.js' %}"></script>
        <script src="{% static 'js/jquery.magnific-popup.min.js' %}"></script>
        <script src="{% static 'js/jquery-asColor.min.js' %}"></script>
        <script src="{% static 'js/jquery-asGradient.js' %}"></script>
        <script src="{% static 'js/jquery-asColorPicker.min.js' %}"></script>
        <script src="{% static 'js/jquery.minicolors.min.js' %}"></script>
        <script src="{% static 'js/jquery.multicheck.js' %}"></script>
        <script src="{% static 'js/jquery.validate.min.js' %}"></script>
        <script src="{% static 'js/toastr.min.js' %}"></script>
        <script src="{% static 'js/select2.full.min.js' %}"></script>
        <script src="{% static 'js/select2.min.js' %}"></script>
        <script src="{% static 'js/jquery.inputmask.bundle.min.js' %}"></script>
        <script src="{% static 'js/quill.min.js' %}"></script>
        <script src="{% static 'js/mask.init.js' %}"></script>
        <script src="{% static 'js/meg.init.js' %}"></script>
        <script src="{% static 'js/cal-init.js' %}"></script>
        <script src="{% static 'constant/strings.js' %}"></script>
        <script src="{% static 'constant/validator.js' %}"></script>
        <script>
            $(document).ready(function () {
                $('#example').DataTable();
            });
        </script>
        <script>
            $(document).ready(function () {
                $('#zero_config').DataTable();
            });
        </script>

    {% block extra_script %}{% endblock extra_script %}

    
    {% endblock script %}

    </body>
    {% endblock body %}


{% endblock html %}

dashboard/myapp/templates/dashboard/charts.html
{% extends "base.html" %}
{% load i18n %}
{% load static %}
{% block extra_css %}
    <style xmlns="http://www.w3.org/1999/html">
    </style>
{% endblock %}
{% block page_title %}
 Chart
{% endblock %}
{% block content %}
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-body d-flex justify-content-center align-items-center">
                        <h5 class="card-title mr-5">Pie Chart for Intensity</h5>
                        <div id="sparkline-chart"></div>
                        {% block extra_script %}
                        <script>
                            $(document).ready(function(){
                                var intensities = {{ intensities|safe }};  
                                var uniqueIntensities = [...new Set(intensities)];
                                $("#sparkline-chart").sparkline(uniqueIntensities, {
                                    type: 'pie',
                                    height: '300px',
                                    width: '400px' 
                                });
                            });
                        </script>
                        {% endblock extra_script %}
                    </div>
                </div>
            </div>
        </div>
    </div>


{% endblock %}

dashboard/myapp/templates/dashboard/includes/footer.html
{% load static %}
  <footer class="footer text-center">
                Visualization Dashboard</a>.
            </footer>

dashboard/myapp/templates/dashboard/includes/header.html
{% load static %}

 <header class="topbar" data-navbarbg="skin5">
            <nav class="navbar fixed-top top-navbar navbar-expand-md navbar-dark">
                <div class="navbar-header" data-logobg="skin5">
                    <a class="navbar-brand" href="index.html">
                        <b class="logo-icon p-l-10">   </b> 
                        <h6>Virtualization Dashboard</h6>
                    </a>
                    <a class="topbartoggler d-block d-md-none waves-effect waves-light" href="javascript:void(0)" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><i class="ti-more"></i></a>
                </div>
                <div class="navbar-collapse collapse" id="navbarSupportedContent" data-navbarbg="skin5">
                    <ul class="navbar-nav float-left mr-auto">
                        <li class="nav-item d-none d-md-block"><a class="nav-link sidebartoggler waves-effect waves-light" href="javascript:void(0)" data-sidebartype="mini-sidebar"><i class="mdi mdi-menu font-24"></i></a></li>
                    </ul>
                </div>
            </nav>
</header>

dashboard/myapp/templates/dashboard/includes/sidebar.html
{% load static %}

<aside class="left-sidebar scrollable ps-container ps-theme-default ps-active-y" data-sidebarbg="skin5">
    <div class="scroll-sidebar">
        <nav class="sidebar-nav">
            <ul id="sidebarnav" class="p-t-30">
                <li class="sidebar-item"> <a class="sidebar-link waves-effect waves-dark sidebar-link" href="{% url 'dashboard:dashboard' %}" aria-expanded="false"><i class="mdi mdi-view-dashboard"></i><span class="hide-menu">Dashboard</span></a></li>
                <li class="sidebar-item"> <a class="sidebar-link waves-effect waves-dark sidebar-link" href="{% url 'dashboard:charts' %}" aria-expanded="false"><i class="mdi mdi-chart-bar"></i><span class="hide-menu">Charts</span></a></li>
                <li class="sidebar-item"> <a class="sidebar-link waves-effect waves-dark sidebar-link" href="{% url 'dashboard:tables' %}" aria-expanded="false"><i class="mdi mdi-border-inside"></i><span class="hide-menu">Tables</span></a></li>
            </ul>
        </nav>
    </div>
</aside>

dashboard/myapp/templates/dashboard/index.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="container-fluid">
        
    <div class="row">
        <div class="col-md-6 col-lg-2 col-xlg-3">
            <div class="card card-hover">
                <div class="box bg-cyan text-center">
                    <h1 class="font-light text-white"><i class="mdi mdi-view-dashboard"></i></h1>
                    <h6 class="text-white">Dashboard</h6>
                </div>
            </div>
        </div>
        
        <div class="col-md-6 col-lg-4 col-xlg-3">
            <div class="card card-hover">
                <div class="box bg-success text-center">
                    <h1 class="font-light text-white"><i class="mdi mdi-chart-areaspline"></i></h1>
                    <h6 class="text-white">Charts</h6>
                </div>
            </div>
        </div>
        
        <div class="col-md-6 col-lg-2 col-xlg-3">
            <div class="card card-hover">
                <div class="box bg-danger text-center">
                    <h1 class="font-light text-white"><i class="mdi mdi-border-outside"></i></h1>
                    <h6 class="text-white">Tables</h6>
                </div>
            </div>
        </div>
    </div>
        
    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="card-body">
                    <div class="d-md-flex align-items-center">
                        <div>
                            <h5 class="card-subtitle">Overview of Dashboard</h5>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-lg-9">
                            <body>
                                <p>This project leverages Django's ORM to create a database from given JSON data and develops a dynamic data visualization dashboard. Utilizing JavaScript and Bootstrap for the front-end, the dashboard incorporates charts-sparkline.js for creative and interactive visualizations. Key variables such as Intensity, Likelihood, Relevance, Year, Country, Topics, and Region are dynamically visualized. The dashboard features user-friendly filters for End Year, Topics, Sector, Region, and Source, providing an intuitive and insightful exploration of the dataset.</p>
                                <div id="chart-container"></div>   
                            </body>
                        </div>
                        <div class="col-lg-3">
                            <div class="row">
                                <div class="col-6 m-t-15 ">
                                    <div class="bg-dark p-10 text-white text-center">
                                        <i class="fa fa-lightbulb"></i>
                                        <h5 class="m-b-0 m-t-5">{{country_count}}</h5>
                                        <small class="font-light">Total Countries</small>
                                    </div>
                                </div>
                                <div class="col-6 m-t-15">
                                    <div class="bg-dark p-10 text-white text-center">
                                        <i class="fa fa-flag"></i>
                                        <h5 class="m-b-0 m-t-5">{{sector_count}}</h5>
                                        <small class="font-light">Total Sector</small>
                                    </div>
                                </div>
                                <div class="col-6 m-t-15">
                                    <div class="bg-dark p-10 text-white text-center">
                                        <i class="fa fa-flag"></i>
                                        <h5 class="m-b-0 m-t-5">{{region_count}}</h5>
                                        <small class="font-light">Total Region</small>
                                    </div>
                                </div>
                                <div class="col-6 m-t-15">
                                    <div class="bg-dark p-10 text-white text-center">
                                        <i class="fa fa-wrench"></i>
                                        <h5 class="m-b-0 m-t-5">{{topics__count}}</h5>
                                        <small class="font-light">Total Topics</small>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

dashboard/myapp/templates/dashboard/tables.html
{% extends "base.html" %}
{% load static %}
{% block page_title %}
 Tables
{% endblock %}
{% block content %}

    <div class="page-breadcrumb">
        <div class="row">
            <div class="col-12 d-flex no-block align-items-center">
                <h4 class="page-title">Tables</h4>
            </div>
        </div>
    </div>
    <div class="container-fluid">
        <div class="row">
            <div class="col-12">
                <div class="card">
                    <div class="card-body">
                        <h5 class="card-title">Dashboard Datatable</h5>
                        <div class="table-responsive">
                            <nav class="navbar navbar-expand-lg navbar-light bg-light">
                                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                                    <span class="navbar-toggler-icon"></span>
                                </button>
                                <div class="collapse navbar-collapse" id="navbarNav">
                                    <ul class="navbar-nav">
                                        <li class="nav-item dropdown">
                                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                                Select Region
                                            </a>
                                            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                                {% for item in region_filter %}
                                                    <a class="dropdown-item" href="?region={{item.region}}">{{item.region}}</a>
                                                {% endfor %}
                                            </div>
                                        </li>
                                        <li class="nav-item dropdown">
                                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                                Select End Year
                                            </a>
                                            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                                <!-- Django code for dropdown items -->
                                                {% for item in endyear_filter %}
                                                    <a class="dropdown-item" href="?end_year={{item.end_year}}">{{item.end_year}}</a>
                                                {% endfor %}
                                            </div>
                                        </li>
                                        <li class="nav-item dropdown">
                                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                                Select Topics
                                            </a>
                                            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                                <!-- Django code for dropdown items -->
                                                {% for item in topics_filter %}
                                                    <a class="dropdown-item" href="?topic={{item.topic}}">{{item.topic}}</a>
                                                {% endfor %}
                                            </div>
                                        </li>
                                        <li class="nav-item dropdown">
                                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                                Select Sector
                                            </a>
                                            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                                <!-- Django code for dropdown items -->
                                                {% for item in sector_filter %}
                                                    <a class="dropdown-item" href="?sector={{item.sector}}">{{item.sector}}</a>
                                                {% endfor %}
                                            </div>
                                        </li>
                                        <li class="nav-item dropdown">
                                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                                Select Source
                                            </a>
                                            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                                <!-- Django code for dropdown items -->
                                                {% for item in source_filter %}
                                                    <a class="dropdown-item" href="?source={{item.source}}">{{item.source}}</a>
                                                {% endfor %}
                                            </div>
                                        </li>
                                    </ul>
                                </div>
                            </nav>
                            
                            <table id="zero_config" class="table table-striped table-bordered">
                                <thead>
                                <tr>
                                    <th>Intensity</th>
                                    <th>Likelihood</th>
                                    <th>Sector</th>
                                    <th>Source</th>
                                    <th>Relevance</th>
                                    <th>Start Year</th>
                                    <th>End Year</th>
                                    <th>Country</th>
                                    <th>Topics</th>
                                    <th>Region</th>
                                </tr>
                                </thead>
                                <tbody>
                                    {% for item in data %}
                                        <tr>
                                            <td>{{ item.intensity }}</td>
                                            <td>{{ item.likelihood  }}</td>
                                            <td>{{ item.sector }}</td>
                                            <td>{{ item.source  }}</td>
                                            <td>{{ item.relevance  }}</td>
                                            <td>{{ item.start_year  }}</td>
                                            <td>{{ item.end_year  }}</td>
                                            <td>{{ item.country  }}</td>
                                            <td>{{ item.topic  }}</td>
                                            <td>{{ item.region  }}</td>
                                        </tr>
                                    {% endfor %}
                                </tbody>
                            </table>
                        </div>

                    </div>
                </div>
            </div>
        </div>

    </div>

{% endblock %}